title: Delamm
description: "Un blog y portfolio personal"
author:
  name: "Delamm"
  email: "dylangoonzalez@outlook.es"
  url: "https://delamm.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Delamm"
year : "2025"
